### ISSUE TITLE
请问如何动态添加后台左侧的菜单项？

### ISSUE THREAD

**Issue by pysjp** [ijry/lyadmin#2]
1.后台左侧的菜单项没有保存到数据库中？
2.如何添加一个模块？在模块管理中没有看到添加按钮

**Comment by ijry** [comment]
您好，在正式文档出来前，可以参考这个http://blog.csdn.net/column/details/corethink-dev.html

发自我的 iPhone

**Comment by pysjp** [comment]
好的 ，非常感谢
