### ISSUE TITLE
想增加后台左侧菜单怎么添加

### ISSUE THREAD

**Issue by lihuafeng** [ijry/lyadmin#6]
想增加后台左侧菜单怎么添加，谢谢！

**Comment by ijry** [comment]
在opencmf.php里添加，具体看官网文档lyadmin.lingyun.net

发自我的 iPhone

**Comment by lihuafeng** [comment]
官网文档都是运营的东西。我也找到在opencmf.php里添加，但是又涉及admin权限限制。估计你们发布的是删减版本，能理解。

**Comment by ijry** [comment]
请仔细看文档二次开发章节，是完整版。

发自我的 iPhone
