### ISSUE TITLE
2.0版本,判断CGI模式代码有问题

### ISSUE THREAD

**Issue by jssnow** [ijry/lyadmin#8]
这是修改后的
define('IS_CGI', (false !== strpos(php_sapi_name, 'cgi') || false !== strpos(php_sapi_name, 'fcgi')) ? 1 : 0);
if (!IS_CLI) {
    // 当前文件名
    if (!defined('_PHP_FILE_')) {
        if (IS_CGI) {
            //CGI/FASTCGI模式下
            $_temp = explode('.php', $_SERVER['PHP_SELF']);
            define('_PHP_FILE_', rtrim(str_replace($_SERVER['HTTP_HOST'], '', $_temp[0] . '.php'), '/'));
        } else {
            define('_PHP_FILE_', rtrim($_SERVER['SCRIPT_NAME'], '/'));
        }
    }
    if (!defined('__ROOT__')) {
        $_root = rtrim(dirname(_PHP_FILE_), '/');
        define('__ROOT__', (('/' == $_root || '\\' == $_root) ? '' : $_root));
    }
}

**Comment by ijry** [comment]
会导致什么问题？

**Comment by jssnow** [comment]
会导致ROOT这个常量定义错误,静态文件路径错误加载不出来

**Comment by Yezipiao** [comment]
666
