### ISSUE TITLE
admin/model/Module

### ISSUE THREAD

**Issue by shehuaqigai** [ijry/lyadmin#9]
case '0': // 禁用
                    $val['right_button']['forbid']['title']               = '启用';
                    $val['right_button']['forbid']['attribute']           = 'class="label label-success-outline label-pill ajax-get" href="' . U('setStatus', array('status' => 'resume', 'ids' => $val['id'])) . '"';
这里的$val['right_button']['forbid']应该是$val['right_button']['resume']吧

**Comment by ijry** [comment]
不是，这是特殊用法。

**Comment by ijry** [comment]
不是，这是特殊用法。
